# Argonne D3 BMW i3 Dataset Pipeline

**MSc Data Science Dissertation**

**Author:** Tarek Noman

**University:** University of East London (UEL)

### Purpose

This notebook builds a reproducible preprocessing pipeline for the Argonne D3 2014 BMW i3 BEV dynamometer dataset.

# Stage 1 — Imports

In [1]:
# ==========================================================
# Imports
# ==========================================================

import os
from pathlib import Path

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

print("Libraries imported successfully.")

Libraries imported successfully.

# Stage 2 — Dataset Paths

In [2]:
# ==========================================================
# Dataset paths
# ==========================================================

PROJECT_ROOT = Path(r"C:\Projects\DS7010_Dissertation")

RAW_DATA_DIR = (
    PROJECT_ROOT
    / "01-Datasets"
    / "03-Argonne_D3"
)

PROCESSED_DATA_DIR = (
    PROJECT_ROOT
    / "02-Processed"
    / "Argonne"
)

PROCESSED_DATA_DIR.mkdir(
    parents=True,
    exist_ok=True
)

print("Project root:", PROJECT_ROOT)
print("Raw Argonne folder exists:", RAW_DATA_DIR.exists())
print("Processed Argonne folder:", PROCESSED_DATA_DIR)

Project root: C:\Projects\DS7010_Dissertation
Raw Argonne folder exists: True
Processed Argonne folder: C:\Projects\DS7010_Dissertation\02-Processed\Argonne

# Stage 3 — Dataset Audit

In [3]:
# ==========================================================
# Stage 3 - Dataset Audit
# ==========================================================

all_files = sorted(RAW_DATA_DIR.rglob("*"))

print("=" * 60)
print("ARGONNE DATASET AUDIT")
print("=" * 60)

print("\nTotal items found:", len(all_files))

print("\nFiles and folders:\n")

for item in all_files:
    print(item.relative_to(RAW_DATA_DIR))

============================================================
ARGONNE DATASET AUDIT
============================================================

Total items found: 29

Files and folders:

2013_Nissan_Leaf
2014_BMW_i3
2014_BMW_i3\61505014 Test Data.txt
2014_BMW_i3\61505015 Test Data.txt
2014_BMW_i3\61505016 Test Data.txt
2014_BMW_i3\61505017 Test Data.txt
2014_BMW_i3\61505018 Test Data.txt
2014_BMW_i3\61505019 Test Data.txt
2014_BMW_i3\61505020 Test Data.txt
2014_BMW_i3\61505021 Test Data.txt
2014_BMW_i3\61505022 Test Data.txt
2014_BMW_i3\61505022_Charge.txt
2014_BMW_i3\61505024 Test Data.txt
2014_BMW_i3\61505025 Test Data.txt
2014_BMW_i3\61505026 Test Data.txt
2014_BMW_i3\61505027 Test Data.txt
2014_BMW_i3\61505027_Charge.txt
2014_BMW_i3\61505028 Test Data.txt
2014_BMW_i3\61505029 Test Data.txt
2014_BMW_i3\61505030 Test Data.txt
2014_BMW_i3\61505030_Charge.txt
2014_BMW_i3\61505039 Test Data.txt
2014_BMW_i3\61505040 Test Data.txt
2014_BMW_i3\61505040_Charge.txt
2014_BMW_i3\61505044 Test Data.txt
2014_BMW_i3\61505045 Test Data.txt
2014_BMW_i3\61505045_Charge.txt
2014_BMW_i3\D3 Master Summary List- 2014 BMW i3 BEV.pdf
2020_Chevrolet_Bolt

In [4]:
# ==========================================================
# Classify BMW i3 files
# ==========================================================

BMW_RAW_DIR = RAW_DATA_DIR / "2014_BMW_i3"

test_files = sorted(
    BMW_RAW_DIR.glob("*Test Data.txt")
)

charge_files = sorted(
    BMW_RAW_DIR.glob("*Charge.txt")
)

summary_files = sorted(
    BMW_RAW_DIR.glob("*.pdf")
)

print("BMW folder exists:", BMW_RAW_DIR.exists())

print("\nTest data files:", len(test_files))
for file_path in test_files:
    print("-", file_path.name)

print("\nCharge files:", len(charge_files))
for file_path in charge_files:
    print("-", file_path.name)

print("\nSummary PDF files:", len(summary_files))
for file_path in summary_files:
    print("-", file_path.name)

BMW folder exists: True

Test data files: 20
- 61505014 Test Data.txt
- 61505015 Test Data.txt
- 61505016 Test Data.txt
- 61505017 Test Data.txt
- 61505018 Test Data.txt
- 61505019 Test Data.txt
- 61505020 Test Data.txt
- 61505021 Test Data.txt
- 61505022 Test Data.txt
- 61505024 Test Data.txt
- 61505025 Test Data.txt
- 61505026 Test Data.txt
- 61505027 Test Data.txt
- 61505028 Test Data.txt
- 61505029 Test Data.txt
- 61505030 Test Data.txt
- 61505039 Test Data.txt
- 61505040 Test Data.txt
- 61505044 Test Data.txt
- 61505045 Test Data.txt

Charge files: 5
- 61505022_Charge.txt
- 61505027_Charge.txt
- 61505030_Charge.txt
- 61505040_Charge.txt
- 61505045_Charge.txt

Summary PDF files: 1
- D3 Master Summary List- 2014 BMW i3 BEV.pdf

# Stage 4 — Schema Validation

In [5]:
# ==========================================================
# Stage 4 - Schema Validation
# ==========================================================

sample_file = test_files[0]

print("Sample file:")
print(sample_file)

# Read one Argonne test file
sample_df = pd.read_csv(
    sample_file,
    sep="\t",
    encoding="latin1"
)

print("\nShape:")
print(sample_df.shape)

print("\nColumns:")
for i, col in enumerate(sample_df.columns):
    print(f"{i:2d} -> {col}")

print("\nFirst five rows:")
display(sample_df.head())

Sample file:
C:\Projects\DS7010_Dissertation\01-Datasets\03-Argonne_D3\2014_BMW_i3\61505014 Test Data.txt

Shape:
(5601, 11)

Columns:
 0 -> Time[sec]
 1 -> Test_Cell_Temp[C]
 2 -> Test_Cell_RH[%]
 3 -> Dyno_Speed[mph]
 4 -> Dyno_Tractive_Effort[N]
 5 -> Phase_#
 6 -> Accelerator_Pedal_Position[%]
 7 -> HV_Battery_SOC[%]
 8 -> HV_Battery_Current[A]
 9 -> HV_Battery_Voltage[V]
10 -> Motor_Speed[rpm]

First five rows:

,Time[sec],Test_Cell_Temp[C],Test_Cell_RH[%],Dyno_Speed[mph],Dyno_Tractive_Effort[N],Phase_#,Accelerator_Pedal_Position[%],HV_Battery_SOC[%],HV_Battery_Current[A],HV_Battery_Voltage[V],Motor_Speed[rpm]
0,-10.0,21.925,47.466,0.0,-11.219,0.0,0.0,56.8,0.650,375.23,0.0
1,-9.9,21.925,47.472,0.0,-11.225,0.0,0.0,56.8,0.650,375.23,0.0
2,-9.8,21.925,47.472,0.0,-11.297,0.0,0.0,56.8,0.644,375.23,0.0
3,-9.7,21.925,47.472,0.0,-11.334,0.0,0.0,56.8,0.646,375.23,0.0
4,-9.6,21.924,47.472,0.0,-11.031,0.0,0.0,56.8,0.644,375.23,0.0

# Stage 5 — Safe Loader

In [6]:
# ==========================================================
# Stage 5 - Safe Argonne Loader
# ==========================================================

def load_argonne_file(file_path):
    """
    Load one Argonne BMW test file safely.
    """

    df = pd.read_csv(
        file_path,
        sep="\t",
        encoding="latin1"
    )

    # Remove pre-test measurements
    df = df[
        df["Time[sec]"] >= 0
    ].copy()

    # Add trip identifier
    trip_id = file_path.stem.replace(" Test Data", "")

    df["Trip_ID"] = trip_id

    return df

In [7]:
# Test loader

test_trip = load_argonne_file(
    test_files[0]
)

print(test_trip.shape)

display(test_trip.head())

print()

print(test_trip["Trip_ID"].unique())

(5501, 12)

,Time[sec],Test_Cell_Temp[C],Test_Cell_RH[%],Dyno_Speed[mph],Dyno_Tractive_Effort[N],Phase_#,Accelerator_Pedal_Position[%],HV_Battery_SOC[%],HV_Battery_Current[A],HV_Battery_Voltage[V],Motor_Speed[rpm],Trip_ID
100,-0.0,21.899,47.597,0.0,-11.150,0.0,0.0,56.8,0.650,375.224,0.0,61505014
101,0.1,21.901,47.597,0.0,-11.357,0.0,0.0,56.8,0.650,375.220,0.0,61505014
102,0.2,21.900,47.599,0.0,-11.153,0.0,0.0,56.8,0.650,375.226,0.0,61505014
103,0.3,21.899,47.599,0.0,-11.359,0.0,0.0,56.8,0.644,375.230,0.0,61505014
104,0.4,21.899,47.599,0.0,-10.939,0.0,0.0,56.8,0.646,375.230,0.0,61505014

<StringArray>
['61505014']
Length: 1, dtype: str

# Stage 6 — Load Test Files

In [8]:
# ==========================================================
# Stage 6 - Load All Test Files
# ==========================================================

all_trips = []

for file_path in test_files:
    try:
        trip = load_argonne_file(file_path)
        all_trips.append(trip)
    except Exception as e:
        print(f"Failed: {file_path.name}")
        print(e)

argonne_all = pd.concat(
    all_trips,
    ignore_index=True
)

print("=" * 60)
print("ARGONNE COMBINED DATASET")
print("=" * 60)

print("\nShape:")
print(argonne_all.shape)

print("\nNumber of trips:")
print(argonne_all["Trip_ID"].nunique())

print("\nTrip IDs:")
print(sorted(argonne_all["Trip_ID"].unique()))

============================================================
ARGONNE COMBINED DATASET
============================================================

Shape:
(507441, 12)

Number of trips:
20

Trip IDs:
['61505014', '61505015', '61505016', '61505017', '61505018', '61505019', '61505020', '61505021', '61505022', '61505024', '61505025', '61505026', '61505027', '61505028', '61505029', '61505030', '61505039', '61505040', '61505044', '61505045']

# Stage 7 — Temporal and Signal Audit

In [9]:
# ==========================================================
# Stage 7 - Temporal Audit
# ==========================================================

print("=" * 60)
print("TEMPORAL AUDIT")
print("=" * 60)

audit = []

for trip_id, trip in argonne_all.groupby("Trip_ID"):

    delta_t = trip["Time[sec]"].diff().dropna()

    audit.append({
        "Trip_ID": trip_id,
        "Rows": len(trip),
        "Start_Time_s": trip["Time[sec]"].min(),
        "End_Time_s": trip["Time[sec]"].max(),
        "Median_dt_s": delta_t.median(),
        "Maximum_dt_s": delta_t.max(),
        "Missing_TimeSteps": (delta_t > 0.11).sum()
    })

audit_df = pd.DataFrame(audit)

display(audit_df)

print("\nSummary:")
display(audit_df.describe())

============================================================
TEMPORAL AUDIT
============================================================

,Trip_ID,Rows,Start_Time_s,End_Time_s,Median_dt_s,Maximum_dt_s,Missing_TimeSteps
0,61505014,5501,-0.0,549.999,0.1,0.1,0
1,61505015,5501,-0.0,549.999,0.1,0.1,0
2,61505016,6933,-0.0,693.199,0.1,0.1,0
3,61505017,8121,-0.0,811.999,0.1,0.1,0
4,61505018,12221,-0.0,1221.999,0.1,0.1,0
5,61505019,48301,-0.0,4829.995,0.1,0.1,0
6,61505020,16101,-0.0,1609.998,0.1,0.1,0
7,61505021,41381,-0.0,4137.996,0.1,0.1,0
8,61505022,5091,-0.0,509.000,0.1,0.1,0
9,61505024,48301,-0.0,4829.995,0.1,0.1,0
10,61505025,12891,-0.0,1288.999,0.1,0.1,0
11,61505026,45531,-0.0,4552.996,0.1,0.1,0
12,61505027,6788,-0.0,678.699,0.1,0.1,0
13,61505028,48301,-0.0,4829.995,0.1,0.1,0
14,61505029,53381,-0.0,5337.995,0.1,0.1,0
15,61505030,930,-0.0,92.900,0.1,0.1,0
16,61505039,48301,-0.0,4829.995,0.1,0.1,0
17,61505040,31129,-0.0,3112.797,0.1,0.1,0
18,61505044,48301,-0.0,4829.995,0.1,0.1,0
19,61505045,14436,-0.0,1443.499,0.1,0.1,0

Summary:

,Rows,Start_Time_s,End_Time_s,Median_dt_s,Maximum_dt_s,Missing_TimeSteps
count,20.00000,20.0,20.000000,2.000000e+01,2.000000e+01,20.0
mean,25372.05000,0.0,2537.102450,1.000000e-01,1.000000e-01,0.0
std,19767.98286,0.0,1976.796353,5.278078e-14,1.594015e-13,0.0
min,930.00000,-0.0,92.900000,1.000000e-01,1.000000e-01,0.0
25%,6896.75000,-0.0,689.574000,1.000000e-01,1.000000e-01,0.0
50%,15268.50000,-0.0,1526.748500,1.000000e-01,1.000000e-01,0.0
75%,48301.00000,0.0,4829.995000,1.000000e-01,1.000000e-01,0.0
max,53381.00000,-0.0,5337.995000,1.000000e-01,1.000000e-01,0.0

In [10]:
print("Trips with missing timestamps:")

display(
    audit_df[
        audit_df["Missing_TimeSteps"] > 0
    ]
)

Trips with missing timestamps:

Empty DataFrame
Columns: [Trip_ID, Rows, Start_Time_s, End_Time_s, Median_dt_s, Maximum_dt_s, Missing_TimeSteps]
Index: []

# Stage 8 — Energy Target Construction

## Step 8.1 — Battery Power

In [11]:
# ==========================================================
# Stage 8.1 - Battery Power
# ==========================================================

# Battery power (W)
argonne_all["Battery_Power_W"] = (
    argonne_all["HV_Battery_Voltage[V]"] *
    argonne_all["HV_Battery_Current[A]"]
)

print("Battery power statistics:")

display(
    argonne_all["Battery_Power_W"].describe()
)

print("\nCharging samples:")
print((argonne_all["Battery_Power_W"] > 0).sum())

print("\nDischarging samples:")
print((argonne_all["Battery_Power_W"] < 0).sum())

print("\nZero-power samples:")
print((argonne_all["Battery_Power_W"] == 0).sum())

Battery power statistics:

count    507441.000000
mean       7035.140724
std       13864.505767
min      -54858.920800
25%         197.397000
50%        4610.468088
75%       13339.869969
max      134384.623450
Name: Battery_Power_W, dtype: float64

Charging samples:
440871

Discharging samples:
66567

Zero-power samples:
3

## Stage 8.1b

In [12]:
# ==========================================================
# Verify current sign convention
# ==========================================================

print("Battery current statistics:\n")

display(
    argonne_all["HV_Battery_Current[A]"].describe()
)

print("\nPositive current samples:")
print((argonne_all["HV_Battery_Current[A]"] > 0).sum())

print("\nNegative current samples:")
print((argonne_all["HV_Battery_Current[A]"] < 0).sum())

print("\nZero current samples:")
print((argonne_all["HV_Battery_Current[A]"] == 0).sum())

Battery current statistics:

count    507441.000000
mean         19.970254
std          39.825164
min        -152.445000
25%           0.534000
50%          12.505000
75%          37.024000
max         401.144000
Name: HV_Battery_Current[A], dtype: float64

Positive current samples:
440871

Negative current samples:
66567

Zero current samples:
3

## Stage 8.2 — Energy Integration

In [13]:
# ==========================================================
# Stage 8.2 - Energy Integration
# ==========================================================

trip_energy = []

for trip_id, trip in argonne_all.groupby("Trip_ID"):

    trip = trip.sort_values("Time[sec]")

    # Time step (seconds)
    dt = trip["Time[sec]"].diff().fillna(0)

    # Incremental energy (Wh)
    trip["Energy_Increment_Wh"] = (
        trip["Battery_Power_W"] * dt / 3600
    )

    # Separate consumption and regeneration
    discharge_energy = (
        trip.loc[
            trip["Energy_Increment_Wh"] > 0,
            "Energy_Increment_Wh"
        ].sum()
    )

    regen_energy = (
        -trip.loc[
            trip["Energy_Increment_Wh"] < 0,
            "Energy_Increment_Wh"
        ].sum()
    )

    net_energy = discharge_energy - regen_energy

    trip_energy.append({

        "Trip_ID": trip_id,

        "Net_Energy_Wh": net_energy,

        "Discharge_Energy_Wh": discharge_energy,

        "Regenerated_Energy_Wh": regen_energy

    })

trip_energy = pd.DataFrame(trip_energy)

display(trip_energy)

print()

print("Summary statistics:")

display(trip_energy.describe())

     Trip_ID  Net_Energy_Wh  Discharge_Energy_Wh  Regenerated_Energy_Wh
0   61505014    1311.626404          1471.057418             159.431014
1   61505015    3776.534038          3793.982568              17.448529
2   61505016    -591.328199          2199.098723            2790.426922
3   61505017    4323.949500          5021.614713             697.665214
4   61505018     897.727553          3888.869880            2991.142327
5   61505019    6312.164304          8012.165188            1700.000883
6   61505020    5797.187135          6505.536052             708.348917
7   61505021    4259.433097          5481.177290            1221.744193
8   61505022    2147.763056          2148.010547               0.247491
9   61505024    7022.218682          8631.395526            1609.176845
10  61505025    4153.425708          4768.404950             614.979242
11  61505026    4834.362376          6032.324158            1197.961782
12  61505027    2754.012694          2799.495133              45.482439
13  61505028    9461.240251         10449.072810             987.832559
14  61505029    8458.484426          9783.331183            1324.846757
15  61505030      20.366958            20.395801               0.028843
16  61505039   11100.313887         12021.914121             921.600235
17  61505040    6516.751510          7396.837617             880.086107
18  61505044   13489.348792         14125.255044             635.906252
19  61505045    3118.555063          3621.393360             502.838297

Summary statistics:

       Net_Energy_Wh  Discharge_Energy_Wh  Regenerated_Energy_Wh
count      20.000000            20.000000              20.000000
mean     4958.206862          5908.566604             950.359742
std      3672.926308          3719.960141             842.415263
min      -591.328199            20.395801               0.028843
25%      2602.450284          3415.918803             416.986476
50%      4291.691298          5251.396002             794.217512
75%      6643.118303          8166.972772            1247.519834
max     13489.348792         14125.255044            2991.142327

## Stage 8.3 — Distance Calculation

In [14]:
# ==========================================================
# Stage 8.3 - Distance Calculation
# ==========================================================

# Convert speed from mph to km/h
argonne_all["Speed_kmh"] = (
    argonne_all["Dyno_Speed[mph]"] * 1.60934
)

trip_distance = []

for trip_id, trip in argonne_all.groupby("Trip_ID"):

    trip = trip.sort_values("Time[sec]")

    dt_hours = trip["Time[sec]"].diff().fillna(0) / 3600

    distance = (
        trip["Speed_kmh"] * dt_hours
    ).sum()

    trip_distance.append({

        "Trip_ID": trip_id,

        "Calculated_Distance_km": distance

    })

trip_distance = pd.DataFrame(trip_distance)

display(trip_distance)

print()

print("Distance statistics:")

display(
    trip_distance["Calculated_Distance_km"].describe()
)

     Trip_ID  Calculated_Distance_km
0   61505014               10.027020
1   61505015               10.019917
2   61505016               10.258211
3   61505017               16.293094
4   61505018               22.415477
5   61505019               53.277096
6   61505020               38.378260
7   61505021               40.518995
8   61505022               13.533568
9   61505024               53.366211
10  61505025               26.705591
11  61505026               40.061816
12  61505027               17.415837
13  61505028               53.465855
14  61505029               53.550514
15  61505030                0.105744
16  61505039               53.468572
17  61505040               35.506188
18  61505044               53.409067
19  61505045               14.888228

Distance statistics:

count    20.000000
mean     30.833263
std      18.618054
min       0.105744
25%      14.549563
50%      31.105890
75%      53.299375
max      53.550514
Name: Calculated_Distance_km, dtype: float64

## Stage 8.4 — Build the Target

In [15]:
# ==========================================================
# Stage 8.4 - Energy Consumption Target
# ==========================================================

# Merge energy and distance
trip_summary = trip_energy.merge(
    trip_distance,
    on="Trip_ID"
)

# Target (kWh/100 km)
trip_summary["Energy_Consumption_kWh_100km"] = (
    trip_summary["Net_Energy_Wh"] /
    trip_summary["Calculated_Distance_km"]
) / 10

print("=" * 60)
print("ARGONNE TARGET")
print("=" * 60)

display(trip_summary)

print("\nTarget statistics:")

display(
    trip_summary["Energy_Consumption_kWh_100km"].describe()
)

============================================================
ARGONNE TARGET
============================================================

,Trip_ID,Net_Energy_Wh,Discharge_Energy_Wh,Regenerated_Energy_Wh,Calculated_Distance_km,Energy_Consumption_kWh_100km
0,61505014,1311.626404,1471.057418,159.431014,10.027020,13.080920
1,61505015,3776.534038,3793.982568,17.448529,10.019917,37.690272
2,61505016,-591.328199,2199.098723,2790.426922,10.258211,-5.764438
3,61505017,4323.949500,5021.614713,697.665214,16.293094,26.538541
4,61505018,897.727553,3888.869880,2991.142327,22.415477,4.004945
5,61505019,6312.164304,8012.165188,1700.000883,53.277096,11.847801
6,61505020,5797.187135,6505.536052,708.348917,38.378260,15.105394
7,61505021,4259.433097,5481.177290,1221.744193,40.518995,10.512188
8,61505022,2147.763056,2148.010547,0.247491,13.533568,15.869896
9,61505024,7022.218682,8631.395526,1609.176845,53.366211,13.158548
10,61505025,4153.425708,4768.404950,614.979242,26.705591,15.552645
11,61505026,4834.362376,6032.324158,1197.961782,40.061816,12.067257
12,61505027,2754.012694,2799.495133,45.482439,17.415837,15.813266
13,61505028,9461.240251,10449.072810,987.832559,53.465855,17.695855
14,61505029,8458.484426,9783.331183,1324.846757,53.550514,15.795337
15,61505030,20.366958,20.395801,0.028843,0.105744,19.260553
16,61505039,11100.313887,12021.914121,921.600235,53.468572,20.760446
17,61505040,6516.751510,7396.837617,880.086107,35.506188,18.353847
18,61505044,13489.348792,14125.255044,635.906252,53.409067,25.256664
19,61505045,3118.555063,3621.393360,502.838297,14.888228,20.946449

Target statistics:

count    20.000000
mean     16.177319
std       8.678003
min      -5.764438
25%      12.827504
50%      15.804302
75%      19.635526
max      37.690272
Name: Energy_Consumption_kWh_100km, dtype: float64

# Stage 9 — Feature Engineering

## Step 9.1 — Calculate Acceleration

In [16]:
# ==========================================================
# Stage 9.1 - Calculate Speed and Acceleration
# ==========================================================

# Speed already converted previously
# Calculate longitudinal acceleration

argonne_all = argonne_all.sort_values(
    ["Trip_ID", "Time[sec]"]
).reset_index(drop=True)

argonne_all["Acceleration_mps2"] = (
    argonne_all
        .groupby("Trip_ID")["Speed_kmh"]
        .diff()
        / 3.6
) / (
    argonne_all
        .groupby("Trip_ID")["Time[sec]"]
        .diff()
)

argonne_all["Acceleration_mps2"] = (
    argonne_all["Acceleration_mps2"]
    .fillna(0)
)

print("Acceleration statistics:")

display(
    argonne_all["Acceleration_mps2"].describe()
)

Acceleration statistics:

count    5.074410e+05
mean    -1.543027e-07
std      6.120254e-01
min     -3.960765e+00
25%     -6.705583e-02
50%      0.000000e+00
75%      8.940778e-02
max      4.653675e+00
Name: Acceleration_mps2, dtype: float64

## Step 9.2 — Build the Machine Learning Features

In [17]:
# ==========================================================
# Stage 9.2 - Trip-level Feature Engineering
# ==========================================================

feature_table = []

for trip_id, trip in argonne_all.groupby("Trip_ID"):

    duration = (
        trip["Time[sec]"].max() -
        trip["Time[sec]"].min()
    )

    feature_table.append({

        "Trip_ID": trip_id,

        # Driving
        "Mean_Speed_kmh": trip["Speed_kmh"].mean(),
        "Max_Speed_kmh": trip["Speed_kmh"].max(),
        "Std_Speed_kmh": trip["Speed_kmh"].std(),

        "Mean_Acceleration_mps2": trip["Acceleration_mps2"].mean(),
        "Max_Acceleration_mps2": trip["Acceleration_mps2"].max(),
        "Min_Acceleration_mps2": trip["Acceleration_mps2"].min(),

        "Mean_Positive_Acceleration_mps2":
            trip.loc[
                trip["Acceleration_mps2"] > 0,
                "Acceleration_mps2"
            ].mean(),

        "Idling_Proportion":
            (trip["Speed_kmh"] < 1).mean(),

        # Battery
        "Start_SOC":
            trip["HV_Battery_SOC[%]"].iloc[0],

        "End_SOC":
            trip["HV_Battery_SOC[%]"].iloc[-1],

        # Environment
        "Mean_Test_Cell_Temp_C":
            trip["Test_Cell_Temp[C]"].mean(),

        "Mean_Test_Cell_RH":
            trip["Test_Cell_RH[%]"].mean(),

        # Vehicle
        "Mean_Motor_RPM":
            trip["Motor_Speed[rpm]"].mean(),

        "Mean_Tractive_Effort_N":
            trip["Dyno_Tractive_Effort[N]"].mean(),

        "Mean_Accelerator_Position":
            trip["Accelerator_Pedal_Position[%]"].mean(),

        "Duration_s":
            duration

    })

feature_table = pd.DataFrame(feature_table)

print(feature_table.shape)

display(feature_table.head())

(20, 17)

,Trip_ID,Mean_Speed_kmh,Max_Speed_kmh,Std_Speed_kmh,Mean_Acceleration_mps2,Max_Acceleration_mps2,Min_Acceleration_mps2,Mean_Positive_Acceleration_mps2,Idling_Proportion,Start_SOC,End_SOC,Mean_Test_Cell_Temp_C,Mean_Test_Cell_RH,Mean_Motor_RPM,Mean_Tractive_Effort_N,Mean_Accelerator_Position,Duration_s
0,61505014,65.619499,129.667742,36.993825,8.208588e-09,1.738981,-1.770274,0.202671,0.038175,56.8,51.1,23.700399,43.220576,4947.948709,135.161228,35.559872,549.999
1,61505015,65.573020,130.531958,36.940607,-2.273323e-16,1.510991,-1.730040,0.257686,0.038538,51.0,34.0,23.434814,44.002443,4962.333101,952.422240,43.213558,549.999
2,61505016,53.266443,134.997877,36.317427,5.944249e-17,4.653675,-3.960765,1.186543,0.133853,33.9,35.8,22.024835,47.323174,4036.762947,-729.452363,12.570771,693.199
3,61505017,72.226525,133.272664,41.516863,-1.095385e-06,4.112758,-2.194961,0.695104,0.137421,35.7,15.1,24.771481,39.660371,5459.873354,490.273510,37.186474,811.999
4,61505018,66.030416,110.420036,39.187552,1.444708e-06,2.266487,-2.485536,0.307318,0.151461,15.0,9.9,24.427732,39.928624,4967.236108,-132.181826,39.161212,1221.999

## Stage 9.3 — Merge the Target

In [18]:
# ==========================================================
# Stage 9.3 - Merge Target
# ==========================================================

argonne_ml = feature_table.merge(
    trip_summary[
        [
            "Trip_ID",
            "Calculated_Distance_km",
            "Net_Energy_Wh",
            "Energy_Consumption_kWh_100km"
        ]
    ],
    on="Trip_ID",
    how="left"
)

print("=" * 60)
print("ARGONNE ML TABLE")
print("=" * 60)

print("\nShape:")
print(argonne_ml.shape)

print("\nMissing values:")
display(argonne_ml.isna().sum())

print("\nDuplicate trips:")
print(argonne_ml["Trip_ID"].duplicated().sum())

display(argonne_ml.head())

============================================================
ARGONNE ML TABLE
============================================================

Shape:
(20, 20)

Missing values:

Trip_ID                            0
Mean_Speed_kmh                     0
Max_Speed_kmh                      0
Std_Speed_kmh                      0
Mean_Acceleration_mps2             0
Max_Acceleration_mps2              0
Min_Acceleration_mps2              0
Mean_Positive_Acceleration_mps2    0
Idling_Proportion                  0
Start_SOC                          0
End_SOC                            0
Mean_Test_Cell_Temp_C              0
Mean_Test_Cell_RH                  0
Mean_Motor_RPM                     0
Mean_Tractive_Effort_N             0
Mean_Accelerator_Position          0
Duration_s                         0
Calculated_Distance_km             0
Net_Energy_Wh                      0
Energy_Consumption_kWh_100km       0
dtype: int64

Duplicate trips:
0

,Trip_ID,Mean_Speed_kmh,Max_Speed_kmh,Std_Speed_kmh,Mean_Acceleration_mps2,Max_Acceleration_mps2,Min_Acceleration_mps2,Mean_Positive_Acceleration_mps2,Idling_Proportion,Start_SOC,End_SOC,Mean_Test_Cell_Temp_C,Mean_Test_Cell_RH,Mean_Motor_RPM,Mean_Tractive_Effort_N,Mean_Accelerator_Position,Duration_s,Calculated_Distance_km,Net_Energy_Wh,Energy_Consumption_kWh_100km
0,61505014,65.619499,129.667742,36.993825,8.208588e-09,1.738981,-1.770274,0.202671,0.038175,56.8,51.1,23.700399,43.220576,4947.948709,135.161228,35.559872,549.999,10.027020,1311.626404,13.080920
1,61505015,65.573020,130.531958,36.940607,-2.273323e-16,1.510991,-1.730040,0.257686,0.038538,51.0,34.0,23.434814,44.002443,4962.333101,952.422240,43.213558,549.999,10.019917,3776.534038,37.690272
2,61505016,53.266443,134.997877,36.317427,5.944249e-17,4.653675,-3.960765,1.186543,0.133853,33.9,35.8,22.024835,47.323174,4036.762947,-729.452363,12.570771,693.199,10.258211,-591.328199,-5.764438
3,61505017,72.226525,133.272664,41.516863,-1.095385e-06,4.112758,-2.194961,0.695104,0.137421,35.7,15.1,24.771481,39.660371,5459.873354,490.273510,37.186474,811.999,16.293094,4323.949500,26.538541
4,61505018,66.030416,110.420036,39.187552,1.444708e-06,2.266487,-2.485536,0.307318,0.151461,15.0,9.9,24.427732,39.928624,4967.236108,-132.181826,39.161212,1221.999,22.415477,897.727553,4.004945

## Stage 9.5 — Target Validation

In [19]:
# ==========================================================
# Stage 9.5 - Target Validation
# ==========================================================

print("=" * 60)
print("TARGET VALIDATION")
print("=" * 60)

print("\nSummary statistics:")

display(
    argonne_ml["Energy_Consumption_kWh_100km"].describe()
)

print("\nNegative consumption trips:")

display(
    argonne_ml[
        argonne_ml["Energy_Consumption_kWh_100km"] < 0
    ][
        [
            "Trip_ID",
            "Calculated_Distance_km",
            "Net_Energy_Wh",
            "Energy_Consumption_kWh_100km"
        ]
    ]
)

print("\nTrips below 5 kWh/100km:")

display(
    argonne_ml[
        (argonne_ml["Energy_Consumption_kWh_100km"] >= 0) &
        (argonne_ml["Energy_Consumption_kWh_100km"] < 5)
    ][
        [
            "Trip_ID",
            "Energy_Consumption_kWh_100km"
        ]
    ]
)

print("\nTrips above 40 kWh/100km:")

display(
    argonne_ml[
        argonne_ml["Energy_Consumption_kWh_100km"] > 40
    ][
        [
            "Trip_ID",
            "Energy_Consumption_kWh_100km"
        ]
    ]
)

============================================================
TARGET VALIDATION
============================================================

Summary statistics:

count    20.000000
mean     16.177319
std       8.678003
min      -5.764438
25%      12.827504
50%      15.804302
75%      19.635526
max      37.690272
Name: Energy_Consumption_kWh_100km, dtype: float64

Negative consumption trips:

,Trip_ID,Calculated_Distance_km,Net_Energy_Wh,Energy_Consumption_kWh_100km
2,61505016,10.258211,-591.328199,-5.764438

Trips below 5 kWh/100km:

    Trip_ID  Energy_Consumption_kWh_100km
4  61505018                      4.004945

Trips above 40 kWh/100km:

Empty DataFrame
Columns: [Trip_ID, Energy_Consumption_kWh_100km]
Index: []

# Stage 10 — Leakage-Safe Modelling Table

In [20]:
# ==========================================================
# Stage 10 - Leakage-Safe ML Table
# ==========================================================

# Keep a complete audit table
argonne_audit = argonne_ml.copy()

# Remove regeneration-dominated trips
argonne_ml_final = argonne_ml[
    argonne_ml["Energy_Consumption_kWh_100km"] >= 0
].copy()

# Remove leakage columns
argonne_ml_final = argonne_ml_final.drop(
    columns=[
        "End_SOC",
        "Calculated_Distance_km",
        "Net_Energy_Wh"
    ]
)

print("=" * 60)
print("ARGONNE LEAKAGE-SAFE ML TABLE")
print("=" * 60)

print("\nAudit table shape:")
print(argonne_audit.shape)

print("\nML table shape:")
print(argonne_ml_final.shape)

print("\nColumns:")

for c in argonne_ml_final.columns:
    print("-", c)

print("\nMissing values:")

display(
    argonne_ml_final.isna().sum()
)

display(argonne_ml_final.head())

============================================================
ARGONNE LEAKAGE-SAFE ML TABLE
============================================================

Audit table shape:
(20, 20)

ML table shape:
(19, 17)

Columns:
- Trip_ID
- Mean_Speed_kmh
- Max_Speed_kmh
- Std_Speed_kmh
- Mean_Acceleration_mps2
- Max_Acceleration_mps2
- Min_Acceleration_mps2
- Mean_Positive_Acceleration_mps2
- Idling_Proportion
- Start_SOC
- Mean_Test_Cell_Temp_C
- Mean_Test_Cell_RH
- Mean_Motor_RPM
- Mean_Tractive_Effort_N
- Mean_Accelerator_Position
- Duration_s
- Energy_Consumption_kWh_100km

Missing values:

Trip_ID                            0
Mean_Speed_kmh                     0
Max_Speed_kmh                      0
Std_Speed_kmh                      0
Mean_Acceleration_mps2             0
Max_Acceleration_mps2              0
Min_Acceleration_mps2              0
Mean_Positive_Acceleration_mps2    0
Idling_Proportion                  0
Start_SOC                          0
Mean_Test_Cell_Temp_C              0
Mean_Test_Cell_RH                  0
Mean_Motor_RPM                     0
Mean_Tractive_Effort_N             0
Mean_Accelerator_Position          0
Duration_s                         0
Energy_Consumption_kWh_100km       0
dtype: int64

,Trip_ID,Mean_Speed_kmh,Max_Speed_kmh,Std_Speed_kmh,Mean_Acceleration_mps2,Max_Acceleration_mps2,Min_Acceleration_mps2,Mean_Positive_Acceleration_mps2,Idling_Proportion,Start_SOC,Mean_Test_Cell_Temp_C,Mean_Test_Cell_RH,Mean_Motor_RPM,Mean_Tractive_Effort_N,Mean_Accelerator_Position,Duration_s,Energy_Consumption_kWh_100km
0,61505014,65.619499,129.667742,36.993825,8.208588e-09,1.738981,-1.770274,0.202671,0.038175,56.8,23.700399,43.220576,4947.948709,135.161228,35.559872,549.999,13.080920
1,61505015,65.573020,130.531958,36.940607,-2.273323e-16,1.510991,-1.730040,0.257686,0.038538,51.0,23.434814,44.002443,4962.333101,952.422240,43.213558,549.999,37.690272
3,61505017,72.226525,133.272664,41.516863,-1.095385e-06,4.112758,-2.194961,0.695104,0.137421,35.7,24.771481,39.660371,5459.873354,490.273510,37.186474,811.999,26.538541
4,61505018,66.030416,110.420036,39.187552,1.444708e-06,2.266487,-2.485536,0.307318,0.151461,15.0,24.427732,39.928624,4967.236108,-132.181826,39.161212,1221.999,4.004945
5,61505019,39.708846,129.123786,35.055462,-2.683094e-07,3.589722,-3.106920,0.410157,0.269705,91.8,22.748966,53.576255,2994.560432,57.148247,24.048655,4829.995,11.847801

# Stage 11 — Export Clean Dataset

In [21]:
# ==========================================================
# Stage 11 - Export Clean Dataset
# ==========================================================

audit_path = PROCESSED_DATA_DIR / "ARGONNE_AUDIT_TABLE.csv"
ml_path = PROCESSED_DATA_DIR / "ARGONNE_ML_TABLE.csv"

argonne_audit.to_csv(
    audit_path,
    index=False
)

argonne_ml_final.to_csv(
    ml_path,
    index=False
)

print("=" * 60)
print("ARGONNE EXPORT COMPLETE")
print("=" * 60)

print("\nAudit dataset:")
print(audit_path)

print("\nMachine Learning dataset:")
print(ml_path)

print("\nAudit shape:", argonne_audit.shape)
print("ML shape:", argonne_ml_final.shape)

============================================================
ARGONNE EXPORT COMPLETE
============================================================

Audit dataset:
C:\Projects\DS7010_Dissertation\02-Processed\Argonne\ARGONNE_AUDIT_TABLE.csv

Machine Learning dataset:
C:\Projects\DS7010_Dissertation\02-Processed\Argonne\ARGONNE_ML_TABLE.csv

Audit shape: (20, 20)
ML shape: (19, 17)

## Argonne Step 1 — verify 20 → 19

In [22]:
print("ARGONNE TARGET AUDIT")
print("=" * 60)

print("Audit observations:", len(argonne_audit))
print("Final ML observations:", len(argonne_ml_final))

print("\nTarget statistics:")
display(
    argonne_audit["Energy_Consumption_kWh_100km"].describe()
)

print("\nNegative targets:",
      (argonne_audit["Energy_Consumption_kWh_100km"] < 0).sum())

print("Zero targets:",
      (argonne_audit["Energy_Consumption_kWh_100km"] == 0).sum())

print("Positive targets:",
      (argonne_audit["Energy_Consumption_kWh_100km"] > 0).sum())

print("\nNon-positive / negative observations:")
display(
    argonne_audit.loc[
        argonne_audit["Energy_Consumption_kWh_100km"] <= 0
    ]
)

ARGONNE TARGET AUDIT
============================================================
Audit observations: 20
Final ML observations: 19

Target statistics:

count    20.000000
mean     16.177319
std       8.678003
min      -5.764438
25%      12.827504
50%      15.804302
75%      19.635526
max      37.690272
Name: Energy_Consumption_kWh_100km, dtype: float64

Negative targets: 1
Zero targets: 0
Positive targets: 19

Non-positive / negative observations:

,Trip_ID,Mean_Speed_kmh,Max_Speed_kmh,Std_Speed_kmh,Mean_Acceleration_mps2,Max_Acceleration_mps2,Min_Acceleration_mps2,Mean_Positive_Acceleration_mps2,Idling_Proportion,Start_SOC,End_SOC,Mean_Test_Cell_Temp_C,Mean_Test_Cell_RH,Mean_Motor_RPM,Mean_Tractive_Effort_N,Mean_Accelerator_Position,Duration_s,Calculated_Distance_km,Net_Energy_Wh,Energy_Consumption_kWh_100km
2,61505016,53.266443,134.997877,36.317427,5.944249e-17,4.653675,-3.960765,1.186543,0.133853,33.9,35.8,22.024835,47.323174,4036.762947,-729.452363,12.570771,693.199,10.258211,-591.328199,-5.764438

## Argonne check

In [23]:
print("ARGONNE POWER SIGN AUDIT")
print("=" * 60)

print("Positive power samples:",
      (argonne_all["Battery_Power_W"] > 0).sum())

print("Negative power samples:",
      (argonne_all["Battery_Power_W"] < 0).sum())

print("Zero power samples:",
      (argonne_all["Battery_Power_W"] == 0).sum())

print("\nTrip energy signs:")
print("Positive net-energy tests:",
      (trip_energy["Net_Energy_Wh"] > 0).sum())

print("Negative net-energy tests:",
      (trip_energy["Net_Energy_Wh"] < 0).sum())

print("\nFirst 10 trip energy results:")
display(
    trip_energy[
        [
            "Trip_ID",
            "Net_Energy_Wh",
            "Discharge_Energy_Wh",
            "Regenerated_Energy_Wh"
        ]
    ].head(10)
)

ARGONNE POWER SIGN AUDIT
============================================================
Positive power samples: 440871
Negative power samples: 66567
Zero power samples: 3

Trip energy signs:
Positive net-energy tests: 19
Negative net-energy tests: 1

First 10 trip energy results:

    Trip_ID  Net_Energy_Wh  Discharge_Energy_Wh  Regenerated_Energy_Wh
0  61505014    1311.626404          1471.057418             159.431014
1  61505015    3776.534038          3793.982568              17.448529
2  61505016    -591.328199          2199.098723            2790.426922
3  61505017    4323.949500          5021.614713             697.665214
4  61505018     897.727553          3888.869880            2991.142327
5  61505019    6312.164304          8012.165188            1700.000883
6  61505020    5797.187135          6505.536052             708.348917
7  61505021    4259.433097          5481.177290            1221.744193
8  61505022    2147.763056          2148.010547               0.247491
9  61505024    7022.218682          8631.395526            1609.176845